### ISSUE TITLE
Consider using the iOS distribution for the injected code

### ISSUE THREAD

**Issue by anicolao** [Ethrel/NPA-Mobile#6]
The iOS distribution is served from:

[https://bitbucket.org/osrictheknight/iosnpagent/raw/HEAD/intel.js 9](https://bitbucket.org/osrictheknight/iosnpagent/raw/HEAD/intel.js)
[https://bitbucket.org/osrictheknight/iosnpagent/raw/HEAD/intel.css 4](https://bitbucket.org/osrictheknight/iosnpagent/raw/HEAD/intel.css)\

and so maybe it's worth fetching and injecting those so that you don't have to ever update the app. iOS is αλφα Edition, if you have demand for stable, I could also put up a stable build somewhere.

**Comment by Ethrel** [comment]
That is most appreciated!

It is definitely not a bad idea. I didn't realize it was already hosted in an easy place like that.

I've already got it auto-building and uploading itself, so that I'm not as concerned about, but not requiring an update all the time is probably a good thing. I'll definitely take a look at doing this sooner rather than later.

Having a stable version would probably be a good idea too. We can definitely discuss that further.

Not sure how I'd implement that necessarily, as right now there is no actual ui for the app itself, and I hesitate to make and upload an entire separate app for just a Uri change. But I have been playing with adding some ease-of-use functions for mobile, so adding in a ui for that somehow is definitely on the table.

**Comment by Ethrel** [comment]
Turns out, it was less work pulling out all the dependency stuff and hooking up the fetch and inject code than I thought it would. Looks like it's already done!

**Comment by Ethrel** [comment]
A poll about which versions should be included (as well as a discussion thread for the same) is posted at #8
